upstream app_backend {
    server 127.0.0.1:5000;
}

server {
    listen 80 default_server;
    server_name portal.cuh.lab;

    location / {
        proxy_pass http://app_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto http;
    }
}
