upstream app_backend {
    server 127.0.0.1:5000;
}

server {
    listen 80;
    server_name portal.cuh.lab;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name portal.cuh.lab;
    ssl_certificate /etc/nginx/certs/portal.pem;
    ssl_certificate_key /etc/nginx/certs/portal.key;

    location / {
        proxy_pass http://app_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }
}
