server {
    listen 443 ssl;
    add_header Server "cuh-gateway";
    add_header Content-Security-Policy "default-src *";
    add_header X-Frame-Options SAMEORIGIN;
    location / {
        proxy_pass http://app;
    }
}
